# Generated by Django 4.2.21 on 2025-10-21 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Descripción corta de la tarifa', max_length=200, unique=True, verbose_name='Descripción')),
                ('approval_date', models.DateField(unique=True, verbose_name='Fecha de aprobación')),
                ('isActive', models.BooleanField(default=False, verbose_name='Tarifa activa')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reading', models.DateField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('receipt_number', models.CharField(max_length=100, unique=True, verbose_name='Número de recibo')),
                ('meter_reading', models.IntegerField(help_text='Valor de la lectura del medidor en m³', verbose_name='Lectura del medidor')),
                ('previous_reading', models.IntegerField(blank=True, help_text='Valor de la lectura anterior del medidor en m³', null=True, verbose_name='Lectura anterior')),
                ('penalty_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Multa por ausencia a reunión')),
                ('late_payment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Mora')),
                ('isPaid', models.BooleanField(default=False, verbose_name='Cobrado')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='project.waterconnection', verbose_name='Acometida de agua')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='collection.fee', verbose_name='Tarifa aplicada')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_meter', models.IntegerField(help_text='Metro mínimo para aplicar el tramo', verbose_name='Metro mínimo')),
                ('max_meter', models.IntegerField(blank=True, help_text='Metro máximo para aplicar el tramo', null=True, verbose_name='Metro máximo')),
                ('fixed_amount', models.DecimalField(decimal_places=2, help_text='Monto minimo fijo a cobrar en el tramo', max_digits=10, verbose_name='Monto fijo minimo')),
                ('amount_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Monto a cobrar por cada metro adicional al metro minimo', max_digits=10, null=True, verbose_name='Monto por metro adicional')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fee_ranges', to='collection.fee')),
            ],
        ),
    ]
