# Generated by Django 4.2.21 on 2025-09-10 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Descripción corta de la tarifa', max_length=200, unique=True, verbose_name='Descripción')),
                ('approval_date', models.DateField(unique=True, verbose_name='Fecha de aprobación')),
                ('isActive', models.BooleanField(default=False, verbose_name='Tarifa activa')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_meter', models.IntegerField(help_text='Metro mínimo para aplicar el tramo', verbose_name='Metro mínimo')),
                ('max_meter', models.IntegerField(blank=True, help_text='Metro máximo para aplicar el tramo', null=True, verbose_name='Metro máximo')),
                ('fixed_amount', models.DecimalField(decimal_places=2, help_text='Monto minimo fijo a cobrar en el tramo', max_digits=10, verbose_name='Monto fijo minimo')),
                ('amount_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Monto a cobrar por cada metro adicional al metro minimo', max_digits=10, null=True, verbose_name='Monto por metro adicional')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fee_ranges', to='collection.fee')),
            ],
        ),
    ]
