# Generated by Django 4.2.21 on 2025-08-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Descripción corta de la tarifa', max_length=200, verbose_name='Descripción')),
                ('approval_date', models.DateField(verbose_name='Fecha de aprobación')),
                ('isActive', models.BooleanField(default=False, verbose_name='Tarifa activa')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo del proyecto', max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logos/', verbose_name='Logo')),
                ('connection_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de acometida')),
                ('absence_fine', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Multa por ausencia a reunión')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_meter', models.IntegerField(help_text='Metro mínimo para aplicar esta tramo', verbose_name='Metro mínimo')),
                ('max_meter', models.IntegerField(help_text='Metro máximo para aplicar esta tramo', verbose_name='Metro máximo')),
                ('fixed_amount', models.DecimalField(decimal_places=2, help_text='Monto minimo fijo a cobrar en esta tramo', max_digits=10, verbose_name='Monto fijo minimo')),
                ('amount_meter', models.DecimalField(decimal_places=2, help_text='Monto a cobrar por cada metro adicional al minimo', max_digits=10, verbose_name='Monto por metro adicional')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fee_ranges', to='project.fee')),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la comunidad', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='project.project')),
            ],
        ),
    ]
