# Generated by Django 4.2.21 on 2025-10-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=project.models.today_local, verbose_name='Fecha de adquisición')),
                ('description', models.CharField(help_text='Descripción corta', max_length=200, unique=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('acquisition_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de adquisición')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_connections', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_connections', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Acometida',
                'verbose_name_plural': 'Acometidas',
                'ordering': ['-date'],
            },
        ),
    ]
