# Generated by Django 4.2.21 on 2025-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la reunión', max_length=200, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('isActive', models.BooleanField(default=True, verbose_name='Reunión activa')),
            ],
        ),
    ]
